/*CONSULTAS*/
USE REPORTES;

/*LISTAR NOMBRE DEL SECTOR*/
SELECT * FROM DBO.SECTOR AS S
WHERE EXISTS(SELECT *
FROM DBO.ASIGNACION_CULTIVO AS AC
WHERE AC.IDSEC = S.IDSEC)
ORDER BY S.NOMSEC

/*LISTAR CULTIVOS POR TIPO EN ORDEN*/
SELECT C.NOMCUL,
    CASE C.TIPCUL 
            WHEN 'PM' THEN 'PERMANENTES'
		    WHEN 'SP' THEN 'SEMI - PERMANENTES'
			WHEN 'TS' THEN 'TRANSITORIOS'
			WHEN 'HT' THEN 'HORTALIZAS'
			WHEN 'OT' THEN 'OTROS'
            END AS TIPCUL
FROM DBO.CULTIVO AS C
ORDER BY CASE WHEN C.TIPCUL = 'PM' THEN 1
		      WHEN C.TIPCUL = 'SP' THEN 2
			  WHEN C.TIPCUL = 'TS' THEN 3
			  WHEN C.TIPCUL = 'HT' THEN 4
			  WHEN C.TIPCUL = 'OT' THEN 5
              END,
			  NOMCUL;

/*LISTA DE CULTIVOS ASIGNADOS*/
SELECT IDASIGCUL, NOMCUL,  
CASE C.TIPCUL 
            WHEN 'PM' THEN 'PERMANENTES'
		    WHEN 'SP' THEN 'SEMI - PERMANENTES'
			WHEN 'TS' THEN 'TRANSITORIOS'
			WHEN 'HT' THEN 'HORTALIZAS'
			WHEN 'OT' THEN 'OTROS'
            END AS TIPCUL , NOMSEC
FROM DBO.ASIGNACION_CULTIVO as AC
    INNER JOIN DBO.CULTIVO AS C ON AC.IDCUL = C.IDCUL
    INNER JOIN DBO.SECTOR AS S ON AC.IDSEC = S.IDSEC
WHERE AC.IDSEC = 19
ORDER BY S.NOMSEC,
CASE WHEN C.TIPCUL = 'PM' THEN 1
		      WHEN C.TIPCUL = 'SP' THEN 2
			  WHEN C.TIPCUL = 'TS' THEN 3
			  WHEN C.TIPCUL = 'HT' THEN 4
			  WHEN C.TIPCUL = 'OT' THEN 5
              END,
			  NOMCUL;

/*LISTA EN JAVA*/
SELECT IDASIGCUL, NOMCUL, TIPCUL, NOMSEC
FROM DBO.ASIGNACION_CULTIVO as AC
    INNER JOIN DBO.CULTIVO AS P ON AC.IDCUL = P.IDCUL
    INNER JOIN DBO.SECTOR AS S ON AC.IDSEC = S.IDSEC
ORDER BY 
NOMSEC,
CASE WHEN TIPCUL = 'PM' THEN 1
WHEN TIPCUL = 'SP' THEN 2
WHEN TIPCUL = 'TS' THEN 3
WHEN TIPCUL = 'HT' THEN 4
 WHEN TIPCUL = 'OT' THEN 5
END,
NOMCUL;