/*INGRESAR CULTIVOS*/
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GRANADA','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MANGO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MANZANO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MELOCOTONERO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PALTO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MANDARINA','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('VID','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ALBARICOQUE','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CIRUELO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('LUCUMO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GRANADILLA','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PERA','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PECANO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GUINDON','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PERA ITALIANA','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ARANDANO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GUAYADO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('KAKI','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MELOCOTON DURAZNO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('TANGELO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('NARANJA','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CIRUELON','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ALFALFA','SP');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ESPARRAGO','SP');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CAÑA DULCE','SP');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('TUNA','SP');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PLATANO ISLA','SP');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GRASS','SP');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('AJI AMARILLO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('AJO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ALGODON TANGUIS','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ALGODON HIBRIDO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ARVERJA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CAMOTE AMARILLO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CAMOTE ROSADO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CEBOLLA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRESA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRIJOL','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MAIZ AMARILLO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MAIZ CHALA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MAIZ CHOCLO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MAIZ MORADO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PALLARES','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PEPINO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PAPA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('TOMATE','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('VAINITA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('YUCA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ZAPALLO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PLATANO','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PAPAYA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HABA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRIJOL GRANO VERDE','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HABAS GRANO VERDE','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PALLAR GRANO VERDE','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ARVERJA GRANO VERDE','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('BERENGENA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('AJI CAPRICA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CEBOLLA ROJA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('QUINUA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CHIA','TS');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRIJOLITO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('COLIFLOR','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HOLANTAO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PIMIENTO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ZANAHORIA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRIJOL CASTILLA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CAIHUA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('BETERRAGA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('APIO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('COL','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CULANTRO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('NABO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PEREJIL','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('COL CHINA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PEPINILLO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('LECHUGA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('BROCOLI','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CULANTRO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PIMIENTON','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PIMIENTO','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ALCACHOFA','HT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRUTALES VARIOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CAÑA BRAVA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PASTOS NATURALES','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MELON','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FORESTALES','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PARQUE ESTADIO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ARANDANO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ESTABLOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HUERTOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MORINGA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PAPAYA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GRAMA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CASA HUERTA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CIRUELON','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FLOR MARIGOLD','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MARACUYA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('OREGANO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HORTALIZAS VARIOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FORREAJE','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('SANDIA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FLORES','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PACAE','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('RUDA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CLABEL','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('VIVERO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ROSAS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GRANJA CAMINOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CASA MALLAS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MANI','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('OREGANO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MARGARITA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HORTALIZAS VARIOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FORRAJE','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ROSAS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('RANJA CAMINOS','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FLOR HORNAMENTAL','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ALVARICOQUE','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('TARA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('FRANHUESA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MORENA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PASTOL NATURAL','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('ESPINO BLANCO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('HIGO','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PIÑA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('PASTO RODA','OT');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('GUANABANO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('MENBRILLO','PM');
Insert into CULTIVO (NOMCUL,TIPCUL) values ('CAMOTE MORADO','TS');

Insert into SECTOR (NOMSEC) values ('Caltopa Caltopilla-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Tunel Grande-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Cantera Almenares-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Roma San Fernando Rinconada-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Ungara-Canal Viejo Imperial');
Insert into SECTOR (NOMSEC) values ('Conde Josefina-Canal Viejo Imperial');
Insert into SECTOR (NOMSEC) values ('Casa Pintada Bandurria-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Cantagallo Union Campesina-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('San Benito-Canal Viejo Imperial');
Insert into SECTOR (NOMSEC) values ('San Jose de Cerro Alegre Y Huaca Chivato-Canal Viejo Imperial');
Insert into SECTOR (NOMSEC) values ('Casa Pintada-Canal Viejo Imperial');
Insert into SECTOR (NOMSEC) values ('San Isidro Compradores-Canal Viejo');
Insert into SECTOR (NOMSEC) values ('La huerta el Cortijo-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Lateral "A"-Quilmana Huaman de los Heros - Canal Nuevo');
Insert into SECTOR (NOMSEC) values ('Lateral "T"-Roldan-Canal Nuevo Imperial');
Insert into SECTOR (NOMSEC) values ('Lateral"B"-San Jose,5 Esquinas-Canal "N" Informacion Estatico a Nivel de Sub Sector Estatico');
Insert into SECTOR (NOMSEC) values ('Lateral"Z"-La Victoria San Fracnisco-Canal Nuevo');
Insert into SECTOR (NOMSEC) values ('Pachacamilla-Canal Pachacamilla');
Insert into SECTOR (NOMSEC) values ('Palo-Canal Herbay');
Insert into SECTOR (NOMSEC) values ('Herbay Alto-Canal Herbay');
Insert into SECTOR (NOMSEC) values ('Herbay Bajo-Canal Herbay');
Insert into SECTOR (NOMSEC) values ('Lucumo Cuiva (Don German Unanue)-Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('Hualcara "A"y"B"-Canal Maria Angola');
Insert into SECTOR (NOMSEC) values ('Montejato Canal Maria Angola');
Insert into SECTOR (NOMSEC) values ('Chilcal-Canal Maria Angola');
Insert into SECTOR (NOMSEC) values ('Huanca Alta Cerro Blanco Unanue-Canal Huaanca Alta');
Insert into SECTOR (NOMSEC) values ('Haunca Media-Tercer Mundo Agua Dulce-Canal Huanca Medio');
Insert into SECTOR (NOMSEC) values ('Tercer Mundo-Canal San Vicente');
Insert into SECTOR (NOMSEC) values ('Tercer Mundo-Canal San Vicente');
Insert into SECTOR (NOMSEC) values ('Casa Blanca Los Lobos-Paguatodos Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('Comunidad Campesina-Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('Tupac Amaru-Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('La Quebrada Tres Cerros-Canal Maria Angola');
Insert into SECTOR (NOMSEC) values ('Santa Barbara-Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('Huanca Baja-San Cruz San Pedro');
Insert into SECTOR (NOMSEC) values ('La Quebrada-La Charilla-Nuevo Mundo-Canal Maria Angola');
Insert into SECTOR (NOMSEC) values ('Las Mellizas-Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('Divididos-Canal San Miguel');
Insert into SECTOR (NOMSEC) values ('Conde Chico-Canal Viejo Imperial');
Insert into SECTOR (NOMSEC) values ('Cerro Alegre 1 y 2');
Insert into SECTOR (NOMSEC) values ('Cerro Alegre 3A 3B 4 y 5-San Jose-Huaca Chivato Parte');
Insert into SECTOR (NOMSEC) values ('Josefina 1 y 2');
Insert into SECTOR (NOMSEC) values ('Gago-El Conde I,II,III-Hualcara Alto');
Insert into SECTOR (NOMSEC) values ('Ungara');

Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('16','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('1','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('11','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('10','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('6','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('3','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('29','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('30','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('23','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('31','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('33','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('78','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('34','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('35','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('84','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('24','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('37','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('38','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('62','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('64','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('39','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('40','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('41','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('42','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('4','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('21','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('43','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('5','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('45','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('44','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('15','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('46','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('47','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('7','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('48','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('49','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('82','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('121','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('77','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('86','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('92','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('65','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('120','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('66','19');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('128','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('10','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('6','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('3','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('4','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('21','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('5','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('12','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('7','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('29','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('30','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('82','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('23','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('32','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('31','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('33','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('34','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('35','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('25','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('36','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('24','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('37','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('38','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('62','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('64','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('39','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('40','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('41','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('42','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('129','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('122','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('43','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('45','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('44','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('46','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('47','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('48','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('66','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('49','20');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('29','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('30','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('82','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('23','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('32','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('33','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('68','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('34','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('130','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('25','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('36','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('24','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('37','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('38','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('52','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('64','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('10','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('39','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('40','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('41','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('42','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('6','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('3','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('4','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('21','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('43','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('5','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('45','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('123','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('44','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('65','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('46','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('47','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('7','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('48','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('66','21');
Insert into ASIGNACION_CULTIVO (IDCUL,IDSEC) values ('49','21');