CREATE DATABASE REPORTES;
USE REPORTES;

--Crear tablas
CREATE TABLE ASIGNACION_CULTIVO
(
	IDASIGCUL int NOT NULL IDENTITY(1, 1),
	IDCUL int NOT NULL,
	IDSEC int NOT NULL,
	CONSTRAINT ASIGNACION_CULTIVO_PK PRIMARY KEY  (IDASIGCUL)
);

CREATE TABLE CULTIVO
(
	IDCUL int NOT NULL IDENTITY(1, 1),
	NOMCUL varchar(100) NOT NULL,
	TIPCUL char(2) NOT NULL,
	CONSTRAINT CULTIVO_PK PRIMARY KEY  (IDCUL)
);

CREATE TABLE SECTOR
(
	IDSEC int NOT NULL IDENTITY(1, 1),
	NOMSEC varchar(100) NOT NULL,
	CONSTRAINT SECTOR_PK PRIMARY KEY  (IDSEC)
);

ALTER TABLE ASIGNACION_CULTIVO ADD CONSTRAINT ASIGNACION_CULTIVO_CULTIVO
    FOREIGN KEY (IDCUL)
    REFERENCES CULTIVO (IDCUL);

ALTER TABLE ASIGNACION_CULTIVO ADD CONSTRAINT ASIGNACION_CULTIVO_SECTOR
    FOREIGN KEY (IDSEC)
    REFERENCES SECTOR (IDSEC);




